server:
 port: 8090

custom:
 blog:
  name: RBlog
# 部署上线需要修改为服务器ip或域名
# api对应后端服务端口 https://api.raxcl.cn/blog
 url:
  api: http://localhost:${server.port}
# cms对应后台管理端口 https://admin.raxcl.cn
  cms: http://localhost:8080
# website对应前台端口 https://raxcl.cn
  website: http://localhost:8081


spring:
 mvc:
  servlet:
   # 路径前缀
   path: /blog
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://81.71.87.241:端口/r_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  username: 用户名
  password: 秘钥
 redis:
  host: 81.71.87.241
  password: 秘钥
  port: 端口
  timeout: 60s
# 阿里云邮箱，port=25在Windows系统下有效，Linux系统需要改为465并将下面两行取消注释，其它邮箱服务商配置参考关键字"spring mail 服务器"
# spring.mail.properties.mail.smtp.socketFactory.port=465
# spring.mail.properties.mail.smtp.ssl.enable=true
 mail:
  host: smtp.qq.com
  # spring.mail.port=465
  username: raxcl@qq.com
  password: 密码
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true
      required: true

mybatis:
 mapper-locations: classpath:mapper/*.xml
 configuration:
  map-underscore-to-camel-case: true

#logging.level.root=info
#logging.level.cn.raxcl=debug
#logging.file=blog-api/log/blog-dev

# 1000 * 60 * 60 * 24 * 3 三天
token:
 expireTime: 259200000
 # 部署上线务必修改此配置，否则无法保证token安全性
 secretKey: 秘钥

# 静态文件上传访问路径 Linux环境如：/home/RBlog/upload/
upload:
 path: /home/RBlog/upload/
 access:
  path: /image/**
 resources:
  locations: file:${upload.path}
  # GitHub token教程见https://raxcl.github.io/PictureHosting/#/pictureHosting/help
 github:
  token: git秘钥
  username: Raxcl
  # 需要用作图床的GitHub仓库名
  repos: blog-resource
  # 需要上传至仓库的路径 开头需要"/" 结尾不要"/"
  repos-path: /comment/avatar