export default {
    myModel:[
      [
        'https://unpkg.com/live2d-widget-model-tororo@1.0.5/assets/tororo.model.json',
        'https://unpkg.com/live2d-widget-model-hijiki@1.0.5/assets/hijiki.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/chiaki_kitty/chiaki_kitty.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/chitose/chitose.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/date_16/date_16.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/epsilon/epsilon.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/hallo_16/hallo_16.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/haru01/haru01.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/haru02/haru02.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/haruto/haruto.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/hibiki/hibiki.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/index/index.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/izumi/izumi.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/jin/jin.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/kanzaki/kanzaki.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/kesshouban/model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/kobayaxi/kobayaxi.model.json',
      ],
      [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/koharu/koharu.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/kuroko/kuroko.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/len/len.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/len_impact/len_impact.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/len_space/len_space.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/len_swim/len_swim.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/mikoto/mikoto.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/miku/miku.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/murakumo/index.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/ni-j/ni-j.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/nico/nico.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/nietzsche/nietzsche.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/nipsilon/nipsilon.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/nito/nito.model.json',

        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/ryoufuku/ryoufuku.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/saten/saten.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/seifuku/seifuku.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/shifuku/shifuku.model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/shifuku2/shifuku2.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/shizuku-48/index.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/shizuku-pajama/index.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/stl/stl.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/touma/touma.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/tsumiki/tsumiki.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/uiharu/uiharu.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/unitychan/unitychan.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/wanko/wanko.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/wed_16/wed_16.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/z16/z16.model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/HK416-1/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/HK416-1/destroy/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/HK416-2/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/HK416-2/destroy/model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/UMP45-1/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/UMP45-1/destroy/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/UMP45-2/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/UMP45-2/destroy/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/UMP45-3/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/UMP45-3/destroy/model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/M4A1-1/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/M4A1-1/destroy/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/M4A1-2/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/M4A1-2/destroy/model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/M4-SOPMOD-II-1/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/M4-SOPMOD-II-1/destroy/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/M4-SOPMOD-II-2/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/M4-SOPMOD-II-2/destroy/model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/WA2000-1/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/WA2000-1/destroy/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/WA2000-2/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/WA2000-2/destroy/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/WA2000-3/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/WA2000-3/destroy/model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/Kar98k/normal/model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/G11/normal/model.json',
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/G11/destroy/model.json',
        ],
        [
        'https://raw.githubusercontent.com/iCharlesZ/vscode-live2d-models/master/model-library/girls-frontline/UMP9/normal/model.json',
        ],
      
    ],
    myMessage:[
      "主人，我来啦~",
    ]
}
